export const POKEDEX_TRY_FETCH = 'POKEDEX_TRY_FETCH'
export const POKEDEX_FETCH_SUCCESS = 'POKEDEX_FETCH_SUCCESS'
export const POKEDEX_FETCH_ERROR = 'POKEDEX_FETCH_ERROR'
export const ADD_POKEMON_TO_TEAM = 'ADD_POKEMON_TO_TEAM'
export const REMOVE_POKEMON_FROM_TEAM = 'REMOVE_POKEMON_FROM_TEAM'
export const CHANGE_POKEMON_NUMBER = "CHANGE_POKEMON_NUMBER"